export const themifyIcons = [
     "ti-circles",
 "ti-notebook ",
 "ti-hanger ",
 "ti-mood-smile",
"ti-device-laptop"
    // 'ti-angle-double-right', 'ti-angle-double-up', 'ti-angle-down', 'ti-angle-left', 'ti-angle-right',
    // 'ti-angle-up', 'ti-arrow-circle-down', 'ti-arrow-circle-left',
    // 'ti-arrow-circle-right', 'ti-arrow-circle-up', 'ti-arrow-down', 'ti-arrow-left', 'ti-arrow-right',
    // 'ti-arrow-top-left', 'ti-arrow-top-right', 'ti-arrow-up', 'ti-attachment', 'ti-back-left',
    // 'ti-back-right', 'ti-bag', 'ti-bar-chart', 'ti-battery', 'ti-beaker', 'ti-bell', 'ti-book',
    // 'ti-bookmark', 'ti-brush', 'ti-briefcase', 'ti-bug', 'ti-building', 'ti-bulb', 'ti-bullet-list',
    // 'ti-calculator', 'ti-calendar', 'ti-camera', 'ti-car', 'ti-cart', 'ti-check', 'ti-check-box',
    // 'ti-check-box-checked', 'ti-check-box-outline-blank', 'ti-check-box-outline-checked',
    // 'ti-check-box-outline-checked-reverse', 'ti-check-box-outline-unchecked', 'ti-check-box-unchecked',
    // 'ti-check-mark', 'ti-clipboard', 'ti-clipboard-alt', 'ti-close', 'ti-cloud', 'ti-cloud-down',
    // 'ti-cloud-up', 'ti-comment', 'ti-comments', 'ti-comments-smiley', 'ti-compass', 'ti-control-backward',
    // 'ti-control-eject', 'ti-control-forward', 'ti-control-pause', 'ti-control-play', 'ti-control-record',
    // 'ti-control-shuffle', 'ti-control-skip-backward', 'ti-control-skip-forward', 'ti-control-stop',
    // 'ti-credit-card', 'ti-crop', 'ti-crown', 'ti-css3', 'ti-cup', 'ti-cursor', 'ti-cut', 'ti-cycle',
    // 'ti-dashboard', 'ti-data', 'ti-database', 'ti-delete', 'ti-direction', 'ti-direction-alt', 'ti-disk',
    // 'ti-document', 'ti-dot-circle-alt', 'ti-download', 'ti-dropbox', 'ti-drupal', 'ti-ebay', 'ti-edit',
    // 'ti-eject', 'ti-envelope', 'ti-exchange-vertical', 'ti-exclamation', 'ti-export', 'ti-eye',
    // 'ti-face-sad', 'ti-face-smile', 'ti-facebook', 'ti-fast-backward', 'ti-fast-forward', 'ti-file',
    // 'ti-files', 'ti-filter', 'ti-flag', 'ti-flash', 'ti-flickr', 'ti-folder', 'ti-folder-open', 'ti-fullscreen',
    // 'ti-galery', 'ti-game', 'ti-gift', 'ti-github', 'ti-google', 'ti-grid-alt', 'ti-grid-slash',
    // 'ti-hand-drag', 'ti-hand-open', 'ti-hand-point-down', 'ti-hand-point-left', 'ti-hand-point-right',
    // 'ti-hand-point-up', 'ti-hand-stop', 'ti-harddrive', 'ti-harddrive-2', 'ti-headphone', 'ti-headphone-alt',
    // 'ti-heart', 'ti-help', 'ti-help-alt', 'ti-home', 'ti-html5', 'ti-image', 'ti-import', 'ti-infinite',
    // 'ti-info', 'ti-info-alt', 'ti-instagram', 'ti-italic', 'ti-joomla', 'ti-jsfiddle', 'ti-key', 'ti-layers',
    // 'ti-layers-alt', 'ti-layout', 'ti-layout-accordion-list', 'ti-layout-accordion-merged',
    // 'ti-layout-accordion-separated', 'ti-layout-column2', 'ti-layout-column2-alt', 'ti-layout-column3',
    // 'ti-layout-column4', 'ti-layout-column4-alt', 'ti-layout-cta-btn-left', 'ti-layout-cta-btn-right',
    // 'ti-layout-cta-center', 'ti-layout-cta-left', 'ti-layout-cta-right', 'ti-layout-grid2',
    // 'ti-layout-grid2-thumb', 'ti-layout-grid3', 'ti-layout-grid4', 'ti-layout-line-solid', 'ti-layout-list-large',
    // 'ti-link', 'ti-linkedin', 'ti-list', 'ti-location-arrow', 'ti-location-pin', 'ti-lock', 'ti-lock-open',
    // 'ti-map', 'ti-map-alt', 'ti-marker', 'ti-marker-alt', 'ti-medall', 'ti-medall-alt', 'ti-menu', 'ti-microphone',
    // 'ti-microsoft', 'ti-microscope', 'ti-minus', 'ti-mobile', 'ti-money', 'ti-mood', 'ti-mouse', 'ti-move',
    // 'ti-music', 'ti-music-alt', 'ti-navigation', 'ti-network', 'ti-new-window', 'ti-notepad', 'ti-notification',
    // 'ti-paint-bucket', 'ti-palette', 'ti-panel', 'ti-pause', 'ti-pause-outline', 'ti-pen', 'ti-pencil',
    // 'ti-pencil-alt', 'ti-phone', 'ti-phone-alt', 'ti-photo', 'ti-photo-alt', 'ti-photo-outline', 'ti-pilcrow',
    // 'ti-pin', 'ti-pin-alt', 'ti-plane', 'ti-plane-outline', 'ti-play', 'ti-play-outline', 'ti-playlist',
    // 'ti-playlist-alt', 'ti-plus', 'ti-power-off', 'ti-printer', 'ti-pulse', 'ti-quote-left', 'ti-quote-right',
    // 'ti-radio-checked', 'ti-radio-unchecked', 'ti-receipt', 'ti-recycle', 'ti-reddit', 'ti-refresh',
    // 'ti-reload', 'ti-repeat', 'ti-resize-full', 'ti-resize-small', 'ti-rss', 'ti-rss-alt', 'ti-ruler',
    // 'ti-ruler-alt', 'ti-safari', 'ti-scissors', 'ti-search', 'ti-share', 'ti-sharethis', 'ti-shield',
    // 'ti-shift-left', 'ti-shift-right', 'ti-shopping-cart', 'ti-sign-in', 'ti-sign-out', 'ti-signal',
    // 'ti-skype', 'ti-slack', 'ti-sliders', 'ti-smallcap', 'ti-soundcloud', 'ti-spell-check', 'ti-split-h',
    // 'ti-split-v', 'ti-spotify', 'ti-stack-overflow', 'ti-star', 'ti-stats-down', 'ti-stats-up', 'ti-stats-dots',
    // 'ti-stats-bars', 'ti-stats-lines', 'ti-stumbleupon', 'ti-subdirectory-left', 'ti-subdirectory-right',
    // 'ti-sun', 'ti-sun-outline', 'ti-support', 'ti-tablet', 'ti-tag', 'ti-tag-alt', 'ti-target', 'ti-text',
    // 'ti-themify-logo', 'ti-themify-logo-circular', 'ti-themify-logo-outline', 'ti-thumb-down', 'ti-thumb-up',
    // 'ti-ticket', 'ti-time', 'ti-timer', 'ti-timer-outline', 'ti-trash', 'ti-trello', 'ti-triangle', 'ti-trophy',
    // 'ti-tumblr', 'ti-tumblr-alt', 'ti-unlink', 'ti-unlock', 'ti-upload', 'ti-user', 'ti-user-add', 'ti-user-delete',
    // 'ti-user-outline', 'ti-video-camera', 'ti-vimeo', 'ti-volume', 'ti-wallet', 'ti-wand', 'ti-warning',
    // 'ti-wifi', 'ti-wikipedia', 'ti-windows', 'ti-wordpress', 'ti-wrench', 'ti-x', 'ti-xbox', 'ti-yahoo',
    // 'ti-youtube', 'ti-zip', 'ti-zoom-in', 'ti-zoom-out'
];
